### ISSUE TITLE
Issue with NoRerverseMatch for 'social_django.urls'?

### ISSUE THREAD

**Issue by eugenma** [RealmTeam/django-rest-framework-social-oauth2#112]
Not sure if its a misconfiguration. But on my system 
- Python 3.6.1
- Windows 10
- Django==1.11.3
- djangorestframework==3.6.3
- django-rest-framework-social-oauth2==1.0.8

I get for the facebook example from the Readme the following exception: 
`django.urls.exceptions.NoReverseMatch: Reverse for 'complete' not found. 'complete' is not a valid view function or pattern name.`

I did tracked it down that it appears at `rest_framework_social_oauth2/oauth2_grants.py: SocialTokenGrant.validate_token_request` at the `reverse` around:

    try:
        backend = load_backend(strategy, request.backend,
                                   reverse(NAMESPACE + ":complete", args=(request.backend,)))
    except MissingBackend...

the reason seams to be that at the `rest_framework_social_oauth2/urls.py` there is:

    url('', include('social_django.urls', namespace="social")),

Since in my applications url i have

    url(r'^auth/', include('rest_framework_social_oauth2.urls', namespace=settings.SOCIAL_AUTH_URL_NAMESPACE)),

with `SOCIAL_AUTH_URL_NAMESPACE='oauth2_provider'

Now to the solution:
replace the reverse above by the following: `reverse(NAMESPACE + ":social:complete", args=(request.backend,)))`

I think the same issue appears with all urls from `social_django.urls`.

So is it a bug? Or did I configured something wrongly?

**Comment by HungryGnu** [comment]
I am having exactly the same issue.  I would love to see a resolution.
