### ISSUE TITLE
Weird issue with QueryDict copy() in views.py

### ISSUE THREAD

**Issue by codebreach** [RealmTeam/django-rest-framework-social-oauth2#136]
I guess this is more of a call for help than an issue:

- When I POST to /auth/token I get `AttributeError("This QueryDict instance is immutable")`

```py
# In TokenView
def post(self, request, *args, **kwargs):
        # Use the rest framework `.data` to fake the post body of the django request.
        print(request._request.POST.__dict__) #1
        request._request.POST = request._request.POST.copy()
        print(request._request.POST.__dict__) #2
        for key, value in request.data.items():
            print(request._request.POST.__dict__) #3
            request._request.POST[key] = value
```

outputs:
```
{'_encoding': 'utf-8', '_mutable': False} #1
{'_encoding': 'utf-8', '_mutable': True} #2
{'_encoding': 'utf-8', '_mutable': False} #3
Internal Server Error: /auth/token
```

I have tried deleting pyc and pycache. Removed site-packages and src from env. Also recreated env always get the same error.

Attaching the debugger is also causing behaviour to change. Also this is happening on multiple machines including mac, ubuntu and alpine.

I am using 
Django 1.11.8
Python 3.6.4

and debugging using VsCode

**Comment by codebreach** [comment]
Also seems that this is caused by DRF 3.7.7

**Comment by adamyala** [comment]
@codebreach I made a PR https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/pull/140 to try and correct this behavior. Super strange. 

Thank you for the print debugging logs. It helped me create a workaround.

**Comment by neural22** [comment]
Any news about this bug? I have also the same problem...

**Comment by adamyala** [comment]
@neural22 I have an open pull request here: https://github.com/RealmTeam/django-rest-framework-social-oauth2/pull/140

If you'd like to use that while this issue/PR is under review, you can use:
```
pip install git+git://github.com/adamyala/django-rest-framework-social-oauth2@mutable-request-data
```
to install from my branch

**Comment by neural22** [comment]
many thanks @adamyala
