### ISSUE TITLE
NotImplementedError at "/auth/convert-token/",  Implement in subclass

### ISSUE THREAD

**Issue by amolc2iq** [RealmTeam/django-rest-framework-social-oauth2#144]
I am trying to convert the social token from backend to access token but getting this NotImplementedError. Attached is the screenshot.

I have followed all the steps from the documentation but still getting this error.

![screen shot 2018-03-27 at 9 55 40 pm](https://user-images.githubusercontent.com/36146081/37980806-a945bf18-3209-11e8-8a5e-9038f0feaabf.png)

**Comment by amolc2iq** [comment]
Going into the details, I found out that the error is raised at:
`return grant_type_handler.create_token_response(
            request, self.default_token_type)`
inside **create_token_response()** method which is defined in **oauth2_endpoints.py** file.

**Comment by PhilipGarnero** [comment]
Backend is not supposed to be `django` but `facebook` or `google`
