### ISSUE TITLE
Can access the API without the token, request for an update to ReadME

### ISSUE THREAD

**Issue by faisaltheparttimecoder** [RealmTeam/django-rest-framework-social-oauth2#146]
Hey team,

Firstly thanks so much for this great library..

So I finished building my django app, worked on to implement DRF social oauth by following the instruction on the README page, everything works, but the only problem was I could access the rest api without the token :) ...

When back to rest framework documentation and figured out there is one line missing that is important to make this library work..

i.e the line below

```
REST_FRAMEWORK = {
    ...
    'DEFAULT_AUTHENTICATION_CLASSES': (
        ...
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
}
```
should be ...

```
REST_FRAMEWORK = {
   .......
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        ...........
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
}
```

Would be great if that above line is added for first timers to Django or Social Auth and to avoid confusion, other than this library works great.... thanks again

Thanks
Faisal

**Comment by PhilipGarnero** [comment]
Hello,
Thanks for your input but we're not going to put that in the readme.
In fact, it is not a requirement for your app to behave correctly and some users will not understand why all their endpoints are protected when they would like some to be open.
The other way around, forces the users to check the django doc about permissions.
