### ISSUE TITLE
What is the use Token returned by /convert-token/ endpoint?

### ISSUE THREAD

**Issue by nikhilponnuru** [RealmTeam/django-rest-framework-social-oauth2#149]
In my android app I get access token of say facebook on client side which I am sending to convert-token endpoint and getting a token back.

I was under the impression that this token returned by convert-token can be used for further requests to my views but I am unable to. instead if i send access token of facebook I am able to access my views

curl -H "Authorization: Bearer <backend_name> <backend_token>" http://localhost:8000/route/to/your/view
here backend token must be facebook access token but not token returned by /convert-token/.

I need some help to understand this. can someone help me?

**Comment by PhilipGarnero** [comment]
When you're using your converted token, simply put `Authorization: Bearer <converted_token>` as a header

**Comment by nikhilponnuru** [comment]
yes I did try that way but it has thrown error saying invalid auth token 400 and then I tried with facebook access token and backend name and it worked

**Comment by nikhilponnuru** [comment]
hey can anyone please make sure it works? 'Authorization: Bearer <converted_token>' this is not working! for accessing views

**Comment by PhilipGarnero** [comment]
The code you're looking at is the custom authentication backend I made which does in fact need a backend part.
However, I did put in the readme that you need two authentication backends with one being         `oauth2_provider.contrib.rest_framework.OAuth2Authentication` that doesn't need the backend part.
Check your settings
