### ISSUE TITLE
Custom user creation with Facebook or Google

### ISSUE THREAD

**Issue by icaboalo** [RealmTeam/django-rest-framework-social-oauth2#152]
I'm implementing facebook and google login, but my user model has more fields that I can get from facebook, for example City or Picture. I want to set them from the beginning when the user is created by calling the convert-token endpoint.

**Comment by PhilipGarnero** [comment]
See [here](https://github.com/python-social-auth/social-docs/blob/master/docs/backends/facebook.rst) for extra fields

**Comment by icaboalo** [comment]
Yes, I can receive the extra fields from facebook, but I want them to be added to my user model when it is created by your library

**Comment by PhilipGarnero** [comment]
You can do that using the python-social-auth pipeline

**Comment by jd-0001** [comment]
Hello @icaboalo can you please share how you done it. I am not so good at auth+social.
Thanks.
