### ISSUE TITLE
Can't convert Token 

### ISSUE THREAD

**Issue by Nkio** [RealmTeam/django-rest-framework-social-oauth2#154]
Hi, 

I am trying to convert token after getting it from [BattleNetOAuth2](http://python-social-auth.readthedocs.io/en/latest/backends/battlenet.html) backend. But, when i try to get access_token with my own client_id and secret_id, i have `{
    "error": "access_denied",
    "error_description": "Your credentials aren't allowed"
}`
I would like to know if someone already seen this issue ? Or maybe i forgot something ?

**Comment by PhilipGarnero** [comment]
You'll have to check with python-social-auth to see if someone can help you there
