### ISSUE TITLE
Working with JWT

### ISSUE THREAD

**Issue by basilbegonia** [RealmTeam/django-rest-framework-social-oauth2#159]
Hi,
I was wondering how one would go about using this alongside JWT? I'd like to authenticate using JWTs after the user logs in using FB/Google. Thanks!

**Comment by PhilipGarnero** [comment]
This is not yet supported because we rely on [django-oauth-toolkit](https://github.com/jazzband/django-oauth-toolkit) for the token handling part.
Please follow [this issue](https://github.com/jazzband/django-oauth-toolkit/issues/397) to get updates about future supports
