### ISSUE TITLE
What do I do after /auth/complete/<social-endpoint>

### ISSUE THREAD

**Issue by ProgrammingJoe** [RealmTeam/django-rest-framework-social-oauth2#164]
I followed the README to the end. I have both a Patreon and a Google app setup. I can make requests to `auth/login/google` and `auth/login/patreon` and the requests are redirected to `auth/complete/patreon` and `auth/complete/google` where "something happens" and then the app is redirected to my redirect URL. At this point the only parameter available is a `session_id` within the GET parameters.

Oauth users are created as well. I'm assuming from here I need to make a request back to google/patreon to get a token that I can then pass through all my requests but how do I do that? All I have is a session id I think?

I assumed I would have a token rather than a session id at this point which is why I'm a bit confused.

Just to clarify, I have a RESTful Django API and a React front-end

**Comment by Tusky** [comment]
I'd be also interested in this. Trying to connect a React front end to Django back end, but after redirecting to backend, finishing the flow, I don't know what should be done, since the Front-end has no idea what's the backend token.

**Comment by PhilipGarnero** [comment]
The `auth/complete/<backend>` routes are used by python-social-auth for authenticating through the django template system. If you're using this library with a client in JS, you should only need `convert-token`.
