### ISSUE TITLE
What after creating access_token

### ISSUE THREAD

**Issue by venkrao** [RealmTeam/django-rest-framework-social-oauth2#171]
Hello, The last paragraph of the documentation states:
> This request returns the "access_token" that you should use on all HTTP requests with DRF. What is happening here is that we are converting a third-party access token (<user_access_token>) in an access token to use with your api and its clients ("access_token"). You should use this token on each and further communications between your system/application and your api to authenticate each request and avoid authenticating with FB every time.

From Django point of view, what's the right way to validate the "access_token" that sent to the backend?

**Comment by PhilipGarnero** [comment]
You don't hava anything to do regarding this point.
The library handles things by itself

**Comment by venkrao** [comment]
I guess I did not explain myself. What's unclear to me is this: How should I send access_token to the backend? How would a view that received this request know that this token belongs to the user that has logged in(in my case, a user that's logged in using google plus)? In my case, `request.user` is set to anonymous user. (for example, the `UserProfileView` shown below.  I'm failing to understand why.
I thought it was for me to implement validation by myself, by querying the table `oauth2_provider_accesstoken` for the access_token, and the user_id that I would have sent from to the backend via request data, because I wasn't sure if such validation is already offered by django-rest-framework-social-oauth2 package already. From the documentation, it wasn't clear if request.user is set by your package or is its something that should be done by the application by calling the `login` method.
I hope I explained myself. 

```
class UserProfileView(CsrfExemptMixin, JSONResponseMixin, APIView):
    def __init__(self):
        pass

    def post(self, request, *args, **kwargs):
        try:
            # TODO: IMPLEMENT is_token_valid()
            userprofile = UserProfile(user_id=Users.objects.get(user_id=request.data.get("user_id")), about_me="",
                                        address=request.data.get("address"), city=request.data.get("city"), state=request.data.get("state"),
                                        postal_code="576200", phone_primary=request.data.get("phone_primary"))

            userprofile.save()
            response_dict = {
                "user_registration": "success"
            }
        except:
            response_dict = {
                "user_registration": "failed"
            }
            raise

        return self.render_json_response(context_dict=response_dict)
```

**Comment by PhilipGarnero** [comment]
Everything is explained in the README.
Simply add an Authorization header as said in the docs.
Please read the readme again.

**Comment by venkrao** [comment]
I got it working. Sorry that I was too impatient to read the README properly. https://www.youtube.com/watch?v=kjp8jYJhujA was equally helpful, too.
