### ISSUE TITLE
Create a django management command to automate the django admin install steps

### ISSUE THREAD

**Issue by jayvdb** [RealmTeam/django-rest-framework-social-oauth2#184]
It would be helpful if the steps in https://github.com/RealmTeam/django-rest-framework-social-oauth2/blob/43e5309/README.rst "Now go to django admin and add a new Application." are exposed as a CLI django management command.

**Comment by bmpenuelas** [comment]
Hi mate, I had the same need, so I wrote this and created PR https://github.com/RealmTeam/django-rest-framework-social-oauth2/pull/197 , I hope it's useful for you too.

**Comment by jayvdb** [comment]
Nice.

**Comment by PhilipGarnero** [comment]
Resolved by #197
