### ISSUE TITLE
Is it possible to customize the new user creation?

### ISSUE THREAD

**Issue by Almaral-Engineering** [RealmTeam/django-rest-framework-social-oauth2#186]
Hi, when a person login for the first time with Facebook it creates a new user and sets the email as username, but when the user's Facebook account is with phone number, it sets the name instead, is it possible to customize this so I can set the phone number in this case instead of the name?

**Comment by PhilipGarnero** [comment]
You'll need to have a look into the facebook backend in python social auth repo
