### ISSUE TITLE
any idea for complete example using google login and update user model using rest api?

### ISSUE THREAD

**Issue by hemanth-sp** [RealmTeam/django-rest-framework-social-oauth2#191]
i searched whole google no proper solution
![Screenshot from 2019-04-20 16-38-11](https://user-images.githubusercontent.com/24698571/56456541-956c0880-638b-11e9-8f45-7184211fd142.png)

**Comment by hemanth-sp** [comment]
https://stackoverflow.com/questions/55779696/error-your-credentials-arent-allowed-in-django-rest-framework-social-oauth2-goo

**Comment by PhilipGarnero** [comment]
Fixed by #201
