### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by beeteax** [RealmTeam/django-rest-framework-social-oauth2#195]
I am using extact json to get token still i am getting errors

**Comment by HeyYouNotYouYou** [comment]
I'm getting the same issue, I set up everything as per the docs but when i send this request
curl -X POST -d "client_id=<id>&client_secret=<secret>&grant_type=password&username=test&password=test@123" http://localhost:8000/auth/token

**Comment by HeyYouNotYouYou** [comment]
my problem was in the urls.py file, I had specified the url in a wrong way

**Comment by ansuman13** [comment]
anyone knows solution to this ?  using django 2.2 and followed up as per docs. shows invalid_client error

**Comment by Barukimang** [comment]
Having the same issue on Django 3.0
