### ISSUE TITLE
Is this still on track to be continuously maintained?

### ISSUE THREAD

**Issue by mizvyt** [RealmTeam/django-rest-framework-social-oauth2#203]
Seems like this repository has not received any updates for almost a year now.
Could we please get an update on the future of this repository?

@PhilipGarnero

**Comment by PhilipGarnero** [comment]
Sorry, this is simply because I'm not currently using this library and that I have a lot going on right now.
I'm updating some things today.
Feel free to send me mails with PRs you'd like merged in the future.

**Comment by akshay1994** [comment]
Hi,

If you are not actively maintaining it, would you be willing to add new maintainers?

**Comment by wagnerdelima** [comment]
Hi, @PhilipGarnero. I have been using this lib for quite a while now. I would like to be a maintainer. If you included me I would be very happy to help!
