### ISSUE TITLE
What do different Authorization grant type do? 

### ISSUE THREAD

**Issue by kautukkundan** [RealmTeam/django-rest-framework-social-oauth2#224]
<img width="445" alt="Screenshot 2020-05-27 at 10 42 56 PM" src="https://user-images.githubusercontent.com/23727056/83051284-6bdfdf00-a06b-11ea-8a65-608083ee94b8.png">

**Comment by wagnerdelima** [comment]
Hi all.

My team and I are constantly using this framework and it seems it has died out there. I contacted the owner by email asking if he would add some of us as maintainers so we could continue to improve it. However we didn't get a response. 

I am publishing the project under my profile and we are going to continue to invest time in it. 

So I would like to gently ask you to contribute to this project on: [https://github.com/wagnerdelima/drf-social-oauth2](url).

Thank you for understanding.
