### ISSUE TITLE
Users must have an phone address

### ISSUE THREAD

**Issue by galizhan** [RealmTeam/django-rest-framework-social-oauth2#229]
Facebook login requires some defining phone address even if didn't specified it in my scopes. However I added phone field in models, but it seems like it didn't affected

```
localhost:8000/auth/convert-token
ValueError at /auth/convert-token
Users must have an phone address
```

**Comment by wagnerdelima** [comment]
Please open future issues at: https://github.com/wagnerdelima/drf-social-oauth2
