### ISSUE TITLE
custom backend not working with convert token api

### ISSUE THREAD

**Issue by Amanb1145** [RealmTeam/django-rest-framework-social-oauth2#248]
I have 3 projects linked to same user model I want that user does not have to login again while visiting any of three websites.
I have a few doubts so far regarding this- 

`DRFSO2_PROPRIETARY_BACKEND_NAME = "VWB"
AUTHENTICATION_BACKENDS = (
    'user.backends.MyAppOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'rest_framework_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)`

I have declared the custom Backend name and AUTHENTICATION_BACKENDS as `'user.backends.MyAuthBackend'`
now when I sign up using user model and get a JWT token and then when I use that token in convert token API, I am getting this error-
`
Exception Type:  NotImplementedError
Exception Value:  Implement in subclass
`
The issue has been fixed.

**Comment by hrahmadi71** [comment]
fra
